ARG AIRFLOW_VERSION=3.3.1
ARG PYTHON_VERSION=3.11
FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

ARG AIRFLOW_VERSION

USER airflow
WORKDIR /opt/airflow/project

COPY --chown=airflow:root pyproject.toml README.md requirements.lock ./
COPY --chown=airflow:root src ./src
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r requirements.lock \
    && pip install --no-cache-dir --no-deps .

COPY --chown=airflow:root configs ./configs
COPY --chown=airflow:root dags ./dags
COPY --chown=airflow:root data/raw/manual ./data/raw/manual
